version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # ánh xạ cổng 8080 từ container sang máy chủ
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-cthheilds78s73f9n1o0-a
      - DB_PORT=5432
      - DB_DATABASE=cafe_gio
      - DB_USERNAME=cafe_gio_user
      - DB_PASSWORD=G63O38PXJaB9O0u5R0WEYCAKwfBU6rjx
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coffee_gio
      POSTGRES_USER: coffee_gio_user
      POSTGRES_PASSWORD: G63O38PXJaB9O0u5R0WEYCAKwfBU6rjx
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
