version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # ánh xạ cổng 8080 từ container sang máy chủ
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-ctfqg4d6l47c73bav820-a
      - DB_PORT=5432
      - DB_DATABASE=coffee_gio
      - DB_USERNAME=coffee_gio_user
      - DB_PASSWORD=LM2bBV3r6lRbD4ALwegKQmRSXVzoJ7R1
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coffee_gio
      POSTGRES_USER: coffee_gio_user
      POSTGRES_PASSWORD: LM2bBV3r6lRbD4ALwegKQmRSXVzoJ7R1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
