version: '3'

services:
  app:
    build: .
    ports:
      - "8080:8080"  # ánh xạ cổng 8080 từ container sang máy chủ
    volumes:
      - .:/var/www
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=dpg-ctgssojtq21c73aau310-a
      - DB_PORT=5432
      - DB_DATABASE=coffee_gio_uxcl
      - DB_USERNAME=coffee_gio_uxcl_user
      - DB_PASSWORD=bbGOVFOw7kBZVVjiBaQFMfuZHH46Inz1
    networks:
      - app_network

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: coffee_gio_uxcl
      POSTGRES_USER: coffee_gio_uxcl_user
      POSTGRES_PASSWORD: bbGOVFOw7kBZVVjiBaQFMfuZHH46Inz1
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
